[google_service_account]
type= "service_account"
project_id= "my-project-skinai"
private_key_id= "64d715d70a0bf53220a1ba750d02a9edeba36e55"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCTu4r/9SP5YNS4
KWWXv2kqZQyVleBR6dSg/1WwAl+HbdrfiaDONNv6fya9Y8RGzEaOrfgQ9QliHO2M
H45HPO26OzM53mlkUcAyVPZnbHxpgNdweLy4YRHwR4d7tUDJ5sldhO5De26q//cE
rRijcCvudNTz8PD+5iufBrIJf4BKUfpFcOF6s2W5IXHlKqfwcW+Q+NLMEBH6BTyd
+Y892MgKJ33JEi+joK1Dhdj14Ls9ZKlbC4LXvXI8F69QRJ9I6fz4MV92+RSP4Ax/
PTJNS3PBiNfQAc7WdzOgzmRBXknfJhC+VB1jx25wsc1BSWGiJzy017fdqNmi2hLi
afKzFFShAgMBAAECggEASBjFL8ADg+8xMQUm6uVDnih9eT0RIfjDR6UEvOaTl2TR
5bjlbO0YFApcrh3TypdjsbsOLrxfDW4/sdwuk+6UuAevKsUz2v0YlpenPvcPSm/R
9DZAJ51b408NPB7LVR1X1VeL7gv9iN9tPm95cD3Mes2ypbBG9KcAz9W1KnR6eAoG
mHsJv6m7PQEUmuT+o8xpuXC8Lb6aZVRgE4HOvvixvL0HS1g5k9iEOBja1DDERJ0t
+k0MM1e/4gdZYL8flg7ZUNKZVVCaN/hfqxkRX+APeCZjjlzYsg5CWTGf/CPwLM5r
ySd4mtxV4iqnohobVpEs3u4I48nnnuHNSbLDjt5qdwKBgQDQnHSpbnO4IuT8NYEE
rxMxnNpkWuoWcHA4Fc/3x8RxRxc9q/4PcraRPfdZG2zTBOYzuZVW2N/cRwzOHcOF
R8CCAxCK+9Og5Cp3k+03g425UeB5aUEu2J0up1UNEw9u6oq/ncXg2R7OdDUtKcbF
WocBv5xcgc0TrpvTDVxgoPyj2wKBgQC1SsN50O8vc7IgpHzzTWHEhCIqFTkD6AI0
7gYfkr0bt0+w3mXsrxc+hMH0XXOYZHkbpgH74zxYRnFPKkvKmyyI7m3xy/4USwCw
+1zg5i8vG0ygt7Horo8iMqz6TYloLq8TCNhnl9qd5Kd7JpaKjaJGnn3stQnB+D/1
+26wzCYQMwKBgEKztA201mVrKuKFzRINVMrJR39NHoo8O3WDa/LjOimqPIEorFyO
Jlf8g0lHnp0+dMjXLywMvk91nF+PXsQP9Drd9f0qljlcm0OO1gupEbjOuEK55/Ct
rFyNfoFmtcmWTvUD4pCJe/MxbwtYz0itMHvbo4hkrIj9jK+IFyCCeSV/AoGAJjJK
XTAYNPc7YIVHjjuPjcgJKrSt/pSzYlOEFsLj9SL6N1mkP+nkC9gMxV+rK0CAA8NG
R7voyvCMjxFqRpXLHE6f+4HvVnc2/hL3zqqw5kvqKTKK2Wtt3Nawe0w61yh+2pPS
hIEKHpo+b0QCE88jkZ1zCpxaIfQcBcej2rwoiOECgYEAtP/tzMI6Gnsq9vkCkV2Z
TO/B+4vwgR/3RT8CamIJADkW4DUiovJ0HD6Aip+P4LxXjNo1R6NTPi13wJPksVRE
XsAHRNEBV0a3Uzg7dt5mgZd//2a5sKP8aRWvdwJpiCrRcFDfduPx9uEoiy9kv2rN
ZIfDMb/O6OWcwl1j8ozdOyQ=
-----END PRIVATE KEY-----
"""
client_email= "eman-741@my-project-skinai.iam.gserviceaccount.com"
client_id= "101472928555180320217"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/eman-741%40my-project-skinai.iam.gserviceaccount.com"
universe_domain= "googleapis.com"
